services:

  node_exporter:
           
    container_name: node_exporter_instance
    build:
      context: ./node_exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - my-network

  prometheus:
    container_name: prometheus_instance
    build:
      context: ./prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-vol:/var/lib/prometheus/data
    networks:
      - my-network

  loki:
    container_name: loki_instance
    build:
      context: ./loki  
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yml:/etc/loki/config.yaml
    command: ["-config.file=/etc/loki/config.yaml"]
    networks:
      - my-network

  promtail:
    container_name: promtail_instance
    image: grafana/promtail:latest
    build:
      context: ./promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yaml
    command: ["-config.file=/etc/promtail/promtail-config.yaml"]  
    networks:
      - my-network    

  grafana:
    container_name: grafana_instance
    build:
      context: ./grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yaml:/usr/local/grafana/conf/provisioning/datasources/datasources.yaml    
    networks:
      - my-network

  nginx:
    container_name: proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/edgar.conf:/etc/nginx/conf.d/edgar.conf
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
    networks:
      - my-network    
volumes:
  prometheus-vol:

networks:
  my-network: